import requests
import time
import re
import os
from bs4 import BeautifulSoup
import pyfiglet

def print_colorful_line(text):
    colors = ['\033[94m', '\033[96m', '\033[97m']
    reset = '\033[0m'
    result = ''
    for i, char in enumerate(text):
        result += colors[i % len(colors)] + char
    return result + reset

def print_colorful_banner(banner_text):
    for line in banner_text.split("\n"):
        print(print_colorful_line(line))

def print_colorful_box():
    reset = '\033[0m'
    text_lines = [
        "SUPPORT : TRAN DUC MINH",
        "DEC BY  : TRAN DUC MINH",
        "ANK LA TRAN DUC MINH W ALEXDZ:))"
    ]
    max_len = max(len(line) for line in text_lines) + 4
    top_bottom = "═" * max_len
    print('\033[96m' + "╔" + top_bottom + "╗" + reset)
    for line in text_lines:
        colorful = print_colorful_line(line)
        padding = max_len - len(line)
        print('\033[94m' + "║  " + colorful + ' ' * (padding - 2) + "║" + reset)
    print('\033[96m' + "╚" + top_bottom + "╝" + reset)

class Messenger:
    def __init__(self, cookie):
        self.cookie = cookie
        self.user_id = self.get_user_id()
        self.fb_dtsg = None
        self.init_params()

    def get_user_id(self):
        match = re.search(r"c_user=(\d+)", self.cookie)
        if match:
            return match.group(1)
        raise Exception("Cookie không hợp lệ")

    def init_params(self):
        headers = {'Cookie': self.cookie, 'User-Agent': 'Mozilla/5.0'}
        for url in ['https://www.facebook.com', 'https://mbasic.facebook.com', 'https://m.facebook.com']:
            response = requests.get(url, headers=headers)
            match = re.search(r'name="fb_dtsg" value="(.*?)"', response.text)
            if match:
                self.fb_dtsg = match.group(1)
                return
        raise Exception("Không tìm thấy fb_dtsg")

    def send_message(self, recipient_id, message):
        timestamp = int(time.time() * 1000)
        data = {
            'fb_dtsg': self.fb_dtsg,
            '__user': self.user_id,
            'body': message,
            'action_type': 'ma-type:user-generated-message',
            'timestamp': timestamp,
            'offline_threading_id': str(timestamp),
            'message_id': str(timestamp),
            'thread_fbid': recipient_id,
            'source': 'source:chat:web',
            'client': 'mercury'
        }
        headers = {
            'Cookie': self.cookie,
            'User-Agent': 'Mozilla/5.0',
            'Content-Type': 'application/x-www-form-urlencoded'
        }
        try:
            response = requests.post('https://www.facebook.com/messaging/send/', data=data, headers=headers)
            return response.status_code == 200
        except:
            return False

def send_messages_loop(messengers, recipient_ids, messages, delay):
    while True:
        for message in messages:
            for recipient_id in recipient_ids:
                for messenger in messengers:
                    success = messenger.send_message(recipient_id, message)
                    status = "ngôn vip" if success else "thất bại khi gữi nội dung"
                    print(f"[{status}] đã gửi tới box: {recipient_id} - Nội dung: {message}")
                    time.sleep(delay)

def main():
    os.system('cls' if os.name == 'nt' else 'clear')

    banner = pyfiglet.figlet_format("MAI THANG LONG", font="big")
    print_colorful_banner(banner)
    print_colorful_box()

    recipient_ids = []
    print("Nhập ID box :")
    while True:
        rid = input("> ").strip()
        if not rid or rid.lower() == 'done':
            break
        recipient_ids.append(rid)

    cookies = []
    print("Nhập cookie:")
    while True:
        c = input("> ").strip()
        if not c or c.lower() == 'done':
            break
        cookies.append(c)

    messengers = []
    for i, cookie in enumerate(cookies, 1):
        try:
            m = Messenger(cookie)
            messengers.append(m)
            print(f"Cookie {i}: OK - User ID: {m.user_id}")
        except Exception as e:
            print(f"Cookie {i}: Lỗi - {e}")

    if not messengers:
        print("cookie không hợp lệ.")
        return

    try:
        delay = float(input("Nhập Delay (khuyến cáo trên 2 đễ tránh mõm và tránh meta quét dân heo way) "))
    except:
        delay = 5

    messages = [
        "bot by Mai Thăng Long , muốn làm hw thì cầm tiền ib em",
        "sao ay👈",
        "sủa mạnh lên em=))",
        "lẹ lên em=))",
        "mạnh mà:))",
        "phế vật vậy em eii=))",
        "sủa mạnh bạo lên cái👈💢💢",
        "đàn ông con trai gì mà ớt v",
        "núp góc niệm phật à🤣🤙",
        "anh là phật sống mà em",
        "sau mà gặp t thì né vội nha=))",
        "em coi chừng bị anh hành đó=))",
        "sủa em",
        "keng cái",
        "sao à🤣",
        "mạnh lên",
        "hăng lên💢",
        "yếu ớt à",
        "speed cái",
        "tốc độ lẹ💢💢👈",
        "chậm chạp vậy🤣",
        "cố lên cái",
        "phế vật🤣",
        "cố mau💢",
        "lẹ cái",
        "run à⁉👈",
        "có nổi kh ấy",
        "anh bá đạo sàn này mà🤣",
        "lag à💢💢🤣",
        "win ak",
        "bá k em=))",
        "noti ak gà:)",
        "ey ey!",
        "sao ds:))💢🤣",
        "còn hăng nổi kh?🤣",
        "sua mau:))",
        "kem v:)",
        "an hai à💢🤣",
        "chat nhanh em⁉",
        "lẹ cái-) ",
        "sàn này anh trùm nhây=))",
        "sồn như lúc đầu cho anh🤣",
        "mạnh mẽ xíu em",
        "lag à con adr ghẻ=))",
        "úi úi🤣",
        "chơi hăng v",
        "chơi hai súng luôn à🤣🤣🤣",
        "eo di bi ti xuất trận đei",
        "sau gặp cha Mai Thăng Long thì xin tha đi=))",
        "ey ey",
        "chạy anh à=))",
        "đâu r",
        "trốn à",
        "44 cmnr🤣",
        "mày thất học à con dốt=))",
        "cạn ngôn r à=))",
        "động não lên xíu đc hơm🤣",
        "chân dài não ngắn à🤣🤣🤣",
        "ăn tí óc chó cho khôn nè:))",
        "chạy đi cầu cứu à ",
        "ysl à:))",
        "dcm anh m bá vl",
        "ăn hại méc mẹ à=))",
        "mày batman ma🤣",
        "nhục v boa",
        "mày bại tlong mà=))",
        "chó đú óc cuttt",
        "ey choancut",
        "conmemaysuanhanh",
        "dot tu ak",
        "hăng hái như lúc đầu cho anh",
        "chet roiiii",
        "dân war 2025 cay anh r:)))",
        "cay rồi thì lmj anh🤣",
        "ngu à em=))",
        "còn cố biện hộ à",
        "ngu thì nhận ngu, đừng cố bào chữa:)",
        "tối qua mẹ m đỉnh lắm em=))",
        "cần anh share link kh🤣",
        "ui ui",
        "mếu à:)))",
        "oc cut bị anh bịa cho do ca daiii",
        "🤣",
        "hài kinh",
        "pỏnk nói cgi v",
        "maithanglong ba san",
        "maithanglong ba san",
        "maithanglong ba san",
        "điều gì quan trọng..",
        "nhắc lại ba lần=))",
        "thangngu còn chờ đợi cgi=))",
        "cầu cứu cứu ak",
        "ai cứu nổi m vậy",
        ":))",
        "trẻ trâu fifai à:)",
        "bucu anh cho mượn máy bắn ff nè=))",
        "ảo à:))",
        "kh có đâu thk nokia",
        "ngôn anh đỉnh cao mà🤣",
        "ai như m",
        "ngôn tiền sữ à:))",
        "bố khỉ🤣",
        "m bị anh chêu cho 44 à🤣",
        "mày hài v em:)",
        "anh em m bỏ m à:)",
        "gặp Mai Thăng Long là sit down 🤣",
        "úi",
        "bê đê gay lọ bịa kinh v",
        "hăng v à",
        "sợ quá anh em🤣🤣🤣",
        "múa như thằng hề cầm dao múa kiếm ở chợ v🤣",
        "cố lên em",
        "sắp win kìa",
        "win mm à=))",
        "mày ngu v ơ=))",
        "nói j cũng tin à",
        "ô ô",
        "sao đó con gay",
        "cố tí",
        "=)))",
        "ey ey",
        "chạy anh à=))",
        "đâu r",
        "trốn à",
        "44 cmnr🤣",
        "mày thất học à con dốt=))",
        "cạn ngôn r à=))",
        "động não lên xíu đc hơm🤣",
        "chân dài não ngắn à🤣🤣🤣",
        "ăn tí óc chó cho khôn nè:))",
        "chạy đi cầu cứu à ",
        "ysl à:))",
        "dcm anh m bá vl",
        "ăn hại méc mẹ à=))",
        "mày batman ma🤣",
        "nhục v boa",
        "mày bại tlong mà=))",
        "chó đú óc cuttt",
        "ey choancut",
        "conmemaysuanhanh",
        "dot tu ak",
        "hăng hái như lúc đầu cho anh",
        "chet roiiii",
        "dân war 2025 cay anh r:)))",
        "cay rồi thì lmj anh🤣",
        "ngu à em=))",
        "còn cố biện hộ à",
        "ngu thì nhận ngu, đừng cố bào chữa:)",
        "tối qua mẹ m đỉnh lắm em=))",
        "cần anh share link kh🤣",
        "ui ui",
        "mếu à:)))",
        "oc cut bị anh bịa cho do ca daiii",
        "🤣",
        "hài kinh",
        "pỏnk nói cgi v",
        "maithanglong ba san",
        "maithanglong ba san",
        "maithanglong ba san",
        "điều gì quan trọng..",
        "nhắc lại ba lần=))",
        "thangngu còn chờ đợi cgi=))",
        "cầu cứu cứu ak",
        "ai cứu nổi m vậy",
        ":))",
        "trẻ trâu fifai à:)",
        "bucu anh cho mượn máy bắn ff nè=))",
        "ảo à:))",
        "kh có đâu thk nokia",
        "ngôn anh đỉnh cao mà🤣",
        "ai như m",
        "ngôn tiền sữ à:))",
        "bố khỉ🤣",
        "m bị anh chêu cho 44 à🤣",
        "mày hài v em:)",
        "anh em m bỏ m à:)",
        "gặp Mai Thăng Long là sit down 🤣",
        "úi",
        "bê đê gay lọ bịa kinh v",
        "hăng v à",
        "sợ quá anh em🤣🤣🤣",
        "múa như thằng hề cầm dao múa kiếm ở chợ v🤣",
        "cố lên em",
        "sắp win kìa",
        "win mm à=))",
        "mày ngu v ơ=))",
        "nói j cũng tin à",
        "ô ô",
        "sao đó con gay",
        "cố tí",
        "=)))",
        "hăng dey🤣",
"ngu à⁉",
"lẹ ey💢🤣:)"
"sủa cái 💢💢🤣",
"lẹ nào ⁉",
"sủa đi:) ",
"phế à",
"thằng gà ",
"hăng đê",
"manh nua⁉ ",
"son ma ",
"ngu ak ⁉",
"tk oc ",
"chat mau🤣",
"s ay💢🤣",
"sua e",
"le e💢🤣",
"manh ma⁉",
"phe ak💢💢🤣",
"tk ga",
"s vay",
"sua cai🤣🤙",
"le ma ⁉",
"o kia ",
"tk ngu💢💢🤣 ",
"manh k ",
"slow ak⁉",
"speed dei",
"phe ak💢🤣",
"phe v ",
"oc cac🤙",
"cn di🤣",
"tat ak⁉",
"clm hai à🤙 ",
"phe vat⁉", 
"sua mau 💢💢🤣",
"em rai🤣",
"manh cai⁉",
"le cai🤣🤙", 
"s do🤣",
"sua e💢💢🤣",
"le em=))", 
"manh di🤣",
"yeu v🤣🤙",
"run aaa",
"keng ngay💢👈",
"keng ma", 
"manh k ⁉",
"sua k🤣👈", 
"sua ak",
"sua de⁉",
"manh chu",
"manh nua💢",
"sao kia em🤣",
"manh ma⁉", 
"phe ak💢💢🤣",
"s kia",
"manh chu⁉",
"tk ngu", 
"sua ak 💢👈",
"sua k",
"son mau⁉",
"hăng dey🤣",
"ngu à⁉",
"lẹ ey💢🤣:)"
"sủa cái 💢💢🤣",
"lẹ nào ⁉",
"sủa đi:) ",
"phế à",
"thằng gà ",
"hăng đê",
"manh nua⁉ ",
"son ma ",
"ngu ak ⁉",
"tk oc ",
"chat mau🤣",
"s ay💢🤣",
"sua e",
"le e💢🤣",
"manh ma⁉",
"phe ak💢💢🤣",
"tk ga",
"s vay",
"sua cai🤣🤙",
"le ma ⁉",
"o kia ",
"tk ngu💢💢🤣 ",
"manh k ",
"slow ak⁉",
"speed dei",
"phe ak💢🤣",
"phe v ",
"oc cac🤙",
"cn di🤣",
"tat ak⁉",
"clm hai à🤙 ",
"phe vat⁉", 
"sua mau 💢💢🤣",
"em rai🤣",
"manh cai⁉",
"le cai🤣🤙", 
"s do🤣",
"sua e💢💢🤣",
"le em=))", 
"manh di🤣",
"yeu v🤣🤙",
"run aaa",
"keng ngay💢👈",
"keng ma", 
"manh k ⁉",
"sua k🤣👈", 
"sua ak",
"sua de⁉",
"manh chu",
"manh nua💢",
"sao kia em🤣",
"manh ma⁉", 
"phe ak💢💢🤣",
"s kia",
"manh chu⁉",
"tk ngu", 
"sua ak 💢👈",
"sua k",
"son mau⁉",
"hăng dey🤣",
"ngu à⁉",
"lẹ ey💢🤣:)"
"sủa cái 💢💢🤣",
"lẹ nào ⁉",
"sủa đi:) ",
"phế à",
"thằng gà ",
"hăng đê",
"manh nua⁉ ",
"son ma ",
"ngu ak ⁉",
"tk oc ",
"chat mau🤣",
"s ay💢🤣",
"sua e",
"le e💢🤣",
"manh ma⁉",
"phe ak💢💢🤣",
"tk ga",
"s vay",
"sua cai🤣🤙",
"le ma ⁉",
"o kia ",
"tk ngu💢💢🤣 ",
      "ysl à:))",
        "dcm anh m bá vl",
        "ăn hại méc mẹ à=))",
        "mày batman ma🤣",
        "nhục v boa",
        "mày bại tlong mà=))",
        "chó đú óc cuttt",
        "ey choancut",
        "conmemaysuanhanh",
        "dot tu ak",
        "hăng hái như lúc đầu cho anh",
        "chet roiiii",
        "dân war 2025 cay anh r:)))",
        "cay rồi thì lmj anh🤣",
        "ngu à em=))",
        "còn cố biện hộ à",
        "ngu thì nhận ngu, đừng cố bào chữa:)",
        "tối qua mẹ m đỉnh lắm em=))",
        "cần anh share link kh🤣",
        "ui ui",
        "mếu à:)))",
        "oc cut bị anh bịa cho do ca daiii",
        "🤣",
        "hài kinh",
        "pỏnk nói cgi v",
        "maithanglong ba san",
        "maithanglong ba san",
        "maithanglong ba san",
        "điều gì quan trọng..",
        "nhắc lại ba lần=))",
        "thangngu còn chờ đợi cgi=))",
        "cầu cứu cứu ak",
        "ai cứu nổi m vậy",
        ":))",
        "trẻ trâu fifai à:)",
        "bucu anh cho mượn máy bắn ff nè=))",
        "ảo à:))",
        "kh có đâu thk nokia",
        "ngôn anh đỉnh cao mà🤣",
        "ai như m",
        "ngôn tiền sữ à:))",
        "bố khỉ🤣",
        "m bị anh chêu cho 44 à🤣",
        "mày hài v em:)",
        "anh em m bỏ m à:)",
        "gặp Mai Thăng Long là sit down 🤣",
        "úi",
        "bê đê gay lọ bịa kinh v",
        "hăng v à",
        "sợ quá anh em🤣🤣🤣",
        "múa như thằng hề cầm dao múa kiếm ở chợ v🤣",
        "cố lên em",
        "sắp win kìa",
        "win mm à=))",
        "mày ngu v ơ=))",
        "nói j cũng tin à",
        "ô ô",
        "sao đó con gay",
        "cố tí",
        "=)))",
        "hăng dey🤣",
"manh k ",
"slow ak⁉",
"speed dei",
"phe ak💢🤣",
"phe v ",
"oc cac🤙",
"cn di🤣",
"tat ak⁉",
"clm hai à🤙 ",
"phe vat⁉", 
"sua mau 💢💢🤣",
"em rai🤣",
"manh cai⁉",
"le cai🤣🤙", 
"s do🤣",
"sua e💢💢🤣",
"le em=))", 
"manh di🤣",
"yeu v🤣🤙",
"run aaa",
"keng ngay💢👈",
"keng ma", 
"manh k ⁉",
"sua k🤣👈", 
"sua ak",
"sua de⁉",
"manh chu",
"manh nua💢",
"sao kia em🤣",
"manh ma⁉", 
"phe ak💢💢🤣",
"s kia",
"manh chu⁉",
"tk ngu", 
"sua ak 💢👈",
"sua k",
"son mau⁉",
"hăng dey🤣",
"ngu à⁉",
"lẹ ey💢🤣:)"
"sủa cái 💢💢🤣",
"lẹ nào ⁉",
"sủa đi:) ",
"phế à",
"thằng gà ",
"hăng đê",
"manh nua⁉ ",
"son ma ",
"ngu ak ⁉",
"tk oc ",
"chat mau🤣",
"s ay💢🤣",
"sua e",
"le e💢🤣",
"manh ma⁉",
"phe ak💢💢🤣",
"tk ga",
"s vay",
"sua cai🤣🤙",
"le ma ⁉",
"o kia ",
"tk ngu💢💢🤣 ",
"manh k ",
"slow ak⁉",
"speed dei",
"phe ak💢🤣",
"phe v ",
"oc cac🤙",
"cn di🤣",
"tat ak⁉",
"clm hai à🤙 ",
      "ysl à:))",
        "dcm anh m bá vl",
        "ăn hại méc mẹ à=))",
        "mày batman ma🤣",
        "nhục v boa",
        "mày bại tlong mà=))",
        "chó đú óc cuttt",
        "ey choancut",
        "conmemaysuanhanh",
        "dot tu ak",
        "hăng hái như lúc đầu cho anh",
        "chet roiiii",
        "dân war 2025 cay anh r:)))",
        "cay rồi thì lmj anh🤣",
        "ngu à em=))",
        "còn cố biện hộ à",
        "ngu thì nhận ngu, đừng cố bào chữa:)",
        "tối qua mẹ m đỉnh lắm em=))",
        "cần anh share link kh🤣",
        "ui ui",
        "mếu à:)))",
        "oc cut bị anh bịa cho do ca daiii",
        "🤣",
        "hài kinh",
        "pỏnk nói cgi v",
        "maithanglong ba san",
        "maithanglong ba san",
        "maithanglong ba san",
        "điều gì quan trọng..",
        "nhắc lại ba lần=))",
        "thangngu còn chờ đợi cgi=))",
        "cầu cứu cứu ak",
        "ai cứu nổi m vậy",
        ":))",
        "trẻ trâu fifai à:)",
        "bucu anh cho mượn máy bắn ff nè=))",
        "ảo à:))",
        "kh có đâu thk nokia",
        "ngôn anh đỉnh cao mà🤣",
        "ai như m",
        "ngôn tiền sữ à:))",
        "bố khỉ🤣",
        "m bị anh chêu cho 44 à🤣",
        "mày hài v em:)",
        "anh em m bỏ m à:)",
        "gặp Mai Thăng Long là sit down 🤣",
        "úi",
        "bê đê gay lọ bịa kinh v",
        "hăng v à",
        "sợ quá anh em🤣🤣🤣",
        "múa như thằng hề cầm dao múa kiếm ở chợ v🤣",
        "cố lên em",
        "sắp win kìa",
        "win mm à=))",
        "mày ngu v ơ=))",
        "nói j cũng tin à",
        "ô ô",
        "sao đó con gay",
        "cố tí",
        "=)))",
        "hăng dey🤣",
"phe vat⁉", 
"sua mau 💢💢🤣",
"em rai🤣",
"manh cai⁉",
"le cai🤣🤙", 
"s do🤣",
"sua e💢💢🤣",
"le em=))", 
"manh di🤣",
"yeu v🤣🤙",
"run aaa",
"keng ngay💢👈",
"keng ma", 
"manh k ⁉",
"sua k🤣👈", 
"sua ak",
"sua de⁉",
"manh chu",
"manh nua💢",
"sao kia em🤣",
"manh ma⁉", 
"phe ak💢💢🤣",
"s kia",
"manh chu⁉",
"tk ngu", 
"sua ak 💢👈",
"sua k",
"son mau⁉",
"hăng dey🤣",
"ngu à⁉",
"lẹ ey💢🤣:)"
"sủa cái 💢💢🤣",
"lẹ nào ⁉",
"sủa đi:) ",
"phế à",
"thằng gà ",
"hăng đê",
"manh nua⁉ ",
"son ma ",
"ngu ak ⁉",
"tk oc ",
"chat mau🤣",
"s ay💢🤣",
"sua e",
"le e💢🤣",
"manh ma⁉",
"phe ak💢💢🤣",
"tk ga",
"s vay",
"sua cai🤣🤙",
"le ma ⁉",
"o kia ",
"tk ngu💢💢🤣 ",
"manh k ",
"slow ak⁉",
"speed dei",
"phe ak💢🤣",
"phe v ",
"oc cac🤙",
"cn di🤣",
"tat ak⁉",
"clm hai à🤙 ",
"phe vat⁉", 
"sua mau 💢💢🤣",
"em rai🤣",
"manh cai⁉",
"le cai🤣🤙", 
"s do🤣",
"sua e💢💢🤣",
"le em=))", 
"manh di🤣",
"yeu v🤣🤙",
"run aaa",
"keng ngay💢👈",
"keng ma", 
"manh k ⁉",
"sua k🤣👈", 
"sua ak",
"sua de⁉",
"manh chu",
"manh nua💢",
"sao kia em🤣",
"manh ma⁉", 
"phe ak💢💢🤣",
"s kia",
"manh chu⁉",
"tk ngu", 
"sua ak 💢👈",
"sua k",
"son mau⁉",
"le mau💢💢👈"
    ]

    print("\n=== Bắt Đầu Gửi Nội Dung Tin Nhắn ===")
    send_messages_loop(messengers, recipient_ids, messages, delay)

if __name__ == "__main__":
    main()
